# Generated by Django 5.0.6 on 2024-06-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='number_question',
            field=models.IntegerField(default=0),
        ),
    ]
